DIR = /var/www/parnik

all: ${DIR}/index.html ${DIR}/nav.html ${DIR}/style.css

${DIR}/index.html: parnik/index.html
	cp $< $@

${DIR}/nav.html: parnik/nav.html
	cp $< $@

${DIR}/style.css: parnik/style.css
	cp $< $@
